### ISSUE TITLE
References to Paper/Dataset

### ISSUE THREAD

**Issue by muellerdo** [anupam-tiwari/Garuda-hack#1]
Hey @anupam-tiwari,

could you please provide references to the paper, original GitHub repository and dataset in this fork.

Cheers,
Dominik Müller

**Comment by anupam-tiwari** [comment]
opps sorry, yeah I will make a commit and include the original Github repo

**Comment by anupam-tiwari** [comment]
Added thanks

**Comment by muellerdo** [comment]
Great, thanks.
